### ISSUE TITLE
Alias @yii/gii will be redefine?

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2-gii#297]
This line make sense?
https://github.com/yiisoft/yii2-gii/blob/4ec2b55e4f0e5a6f27be93b4a1618a727409dec5/tests/bootstrap.php#L15

I test similar code... 
And in my case similar alias in unit test is change after check composer dependences (I had to define another low-level alias) `var_dump(Yii::$aliases);`:
```
/project/tests/bootstrap.php:16:
array(2) {
  '@yii' =>
  string(28) "/project/vendor/yiisoft/yii2"
  '@bscheshirwork' =>
  array(3) {
    '@bscheshirwork/cubs/tests/unit' =>
    string(14) "/project/tests"
    '@bscheshirwork/cubs/generators' =>
    string(23) "/project/src/generators"
    '@bscheshirwork/cubs' =>
    string(12) "/project/src"
  }
}
```
see `@bscheshirwork/cubs` - applying from composer alias, not from bootstrap
```
/project/vendor/yiisoft/yii2-gii/Generator.php:333:
array(7) {
  '@yii' =>
  array(3) {
    '@yii/gii' =>
    string(32) "/project/vendor/yiisoft/yii2-gii"
    '@yii/bootstrap' =>
    string(38) "/project/vendor/yiisoft/yii2-bootstrap"
    '@yii' =>
    string(28) "/project/vendor/yiisoft/yii2"
  }
  '@bscheshirwork' =>
  array(3) {
    '@bscheshirwork/cubs/tests/unit' =>
    string(14) "/project/tests"
    '@bscheshirwork/cubs/generators' =>
    string(23) "/project/src/generators"
    '@bscheshirwork/cubs' =>
    string(43) "/project/vendor/bscheshirwork/yii2-cubs/src"
  }
  '@app' =>
  string(14) "/project/tests"
  '@vendor' =>
  string(15) "/project/vendor"
  '@bower' =>
  string(21) "/project/vendor/bower"
  '@npm' =>
  string(19) "/project/vendor/npm"
  '@runtime' =>
  string(22) "/project/tests/runtime"
}
```

**Comment by samdark** [comment]
Have you checked it when running tests?

**Comment by bscheshirwork** [comment]
> Have you checked it when running tests?
Yes, it's correct. Just place `var_dump` and `exit` to terminate and show stdout.

**Comment by bscheshirwork** [comment]
I can check it on yii2-gii some bit letter

**Comment by bscheshirwork** [comment]
NOT confirmed.

I use same docker images
```yml
version: '2'
services:
  php:
    image: bscheshir/codeception:php7.1.9-fpm-yii2 #contain phpunit
    volumes:
      - ..:/project #src and tests shared to container
      - ~/.composer/cache:/root/.composer/cache
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=192.168.0.83 remote_port=9002 remote_enable=On"
      PHP_IDE_CONFIG: "serverName=codeception"
    depends_on:
      - pgsql
  pgsql:
    image: postgres:9.6.5
    environment:
      TZ: Europe/Moscow
      POSTGRES_PASSWORD: yii2advanced
      POSTGRES_DB: yii2advanced
      POSTGRES_USER: yii2advanced

```

```bash
docker-compose://[/home/dev/projects/yii2-gii/tests/docker-compose.yml]:php/php /repo/vendor/phpunit/phpunit/phpunit --configuration /project/phpunit.xml.dist --teamcity
Testing started at 16:00 ...
/project/tests/bootstrap.php:16:
array(2) {
  '@yii' =>
  array(2) {
    '@yii/gii' =>
    string(8) "/project"
    '@yii' =>
    string(28) "/project/vendor/yiisoft/yii2"
  }
  '@yiiunit' =>
  array(1) {
    '@yiiunit/extensions/gii' =>
    string(14) "/project/tests"
  }
}
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

/project/Generator.php:333:
array(7) {
  '@yii' =>
  array(3) {
    '@yii/gii' =>
    string(8) "/project"
    '@yii/bootstrap' =>
    string(38) "/project/vendor/yiisoft/yii2-bootstrap"
    '@yii' =>
    string(28) "/project/vendor/yiisoft/yii2"
  }
  '@yiiunit' =>
  array(1) {
    '@yiiunit/extensions/gii' =>
    string(14) "/project/tests"
  }
  '@app' =>
  string(14) "/project/tests"
  '@vendor' =>
  string(15) "/project/vendor"
  '@bower' =>
  string(21) "/project/vendor/bower"
  '@npm' =>
  string(19) "/project/vendor/npm"
  '@runtime' =>
  string(22) "/project/tests/runtime"
}

Process finished with exit code 0
```
